ALTER TABLE Materias_Primas AUTO_INCREMENT= 16;


INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (20,'Leche','Ultrapasteurizada',12.90,250,10,240,'2013-01-01','Litros');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (22,'Harina','Harina blanca',11.20,250,10,230,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (44,'Huevo','18 piezas',32.20,250,15,240,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (1,'Crema Chantillí','5kg por carton',75.00,240,10,225,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (10,'Azucar','Azucar morena agranel',14.90,280,20,290,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (28,'Mantequilla','Con sal',93.00,250,30,280,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (33,'Levadura','Royal',17.45,205,12,206,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (3,'Cacao','Hershys',45.76,205,12,206,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (16,'Chocolate','Amargo',60.00,205,12,206,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (33,'Nuez','Moscada',72.00,208,13,206,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (7,'Vainilla','Extracto',33.80,205,11,202,'2013-01-01','Litros');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (21,'Piña','En almibar',38.89,204,11,206,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (38,'Durazno','En almibar',43.50,204,11,202,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (46,'Fresa','Pico de pàjaro',34.67,212,14,218,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (15,'Queso crema','-------',79.00,208,13,206,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (18,'Manzana','Red delicious',18.30,206,12,214,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (12,'Menta','Extracto',130.00,202,11,211,'2013-01-01','Litros');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (28,'Azùcar glass','Ultrafina',13.45,204,12,212,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (9,'Limon','Concentrado',65.00,203,11,212,'2013-01-01','Litros');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (36,'Semilla de amapola','Importada',67.80,202,11,211,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (22,'Sal','La Fina',7.00,205,12,213,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (22,'Bicarbonato de sodio','Puro',16.00,202,11,212,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (36,'Chispas de chocolate','Semiamargo',37.00,204,12,223,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (10,'Canela','En polvo',60.00,201,11,221,'2013-01-01','Kilogramos');
INSERT INTO `Materias_Primas` (`id_proveedor`,`nombre`,`descripcion`,`precio`,`stock`,`stock_minimo`,`stock_maximo`,`fecha_ingreso`,`unidad`) VALUES (32,'Colorante rojo','Para red velvet',27.50,201,11,22,'2013-01-01','Kilogramos');
